parameters:
    key_googlemaps: XXXXXXXXXXX
    position_entity: XXXXXXXXXX
    position_repository: XXXXXXXXXX
    core.map.class:  MadForWebs\GoogleMapsBundle\Service\Map

services:
    core.map:
        class: "%core.map.class%"
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@service_container'
            - '%key_googlemaps%'
            - '%position_entity%'
            - '%position_repository%'
