<?php

namespace MadForWebs\GoogleMapsBundle\Repository;

/**
 * PositionCPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionCPRepository extends \Doctrine\ORM\EntityRepository
{
}
